### ISSUE TITLE
register

### ISSUE THREAD

**Issue by cfhaak** [bundesverfassung-oesterreich/bv-entities#3]
From the hkw-project I recieved some index-data as a xml dump from exist-db. 
1. Laws
2. Persons
3. Terms & Definitions
Contents look realy good eg.:
``` xml
            <bibl type="statute" xml:id="ed_ty3_zkg_ktb">
               <title type="short"/>
               <title type="reg">[Revidierte] Verfassungsurkunde für den preußischen Staat, vom 31. Januar 1850, Preußische Gesetz-Sammlung, S. 17</title>
               <pubPlace>Deutschland</pubPlace>
               <linkGrp>
                  <ptr type="volume" target="HKW 2"/>
               </linkGrp>
            </bibl>
```
or 
``` xml
      <person xml:id="ed_avc_smx_3tb">
            <idno type="uri">https://d-nb.info/gnd/136105386</idno>
            <persName type="reg">
                  <surname/>
                  <forename>Mazzino </forename>
            </persName>
            <birth>1928</birth>
            <death>1986</death>
      </person>
```
or
``` xml
          <item xml:id="s_N1.5.2.2.4">
             <label type="reg">Adjustierung</label>
             <desc>Adjustierung bedeutet im österreichischen Militärjargon die Uniformart bzw. die
                befohlene Bekleidung und Ausrüstung (z. B. Paradeadjustierung,
                Feldadjustierung).</desc>
             <listRef>
                <ptr type="note" target="HKW 5-497.144"/>
             </listRef>
          </item>
```
How do we deal with this data?
In my opinion, the best would be to write these data to baserow-tables and keep all the information. This would be an one-time import without the intention to repeat it after the data where modified. This would mean to "fork", without beeing able to "merge" later on. (Even though it might be possible,, eg. if dnb-identifier would be matched eg.). I would keep the hkw identifier in a field but create new ones for the project. 
Does that sound allright @csae8092  ?

**Comment by cfhaak** [comment]
(Okay, Mazzino wasn't the best example, since surname is missing. Might be an error.)

**Comment by csae8092** [comment]
> Does that sound allright?

Generally speaking yes. The only potential negativ thing is that we might bloat our register (e.g. Persons) with many many entries which will never ever be referenced by our documents. Which doesn't matter much in regards of the web application because we can easly kick out all not mentioned entites from the index files via script ...

so actually my way to go would be to simply add a new column to the baserow tables called hkw_id and let the editors/curators add the hkw ids into it. 

if it turns out later that (some) entities types have a significant overlap, than you can start scripting as described above

**Comment by cfhaak** [comment]
registers will not be used
